name: on-issue-create

on:
  issues:
    types:
    - opened
    - edited

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create file
      run: | 
        file="files/${{ github.event.issue.number }}.md"

        # Proper sanitation: ensure directory exists and remove file if already there
        mkdir -p files
        rm $file || true
        
        touch $file
        echo "# Title" >> $file
        echo "" >> $file
        echo "${{ github.event.issue.body }}" >> $file

    - name: Commit new issue
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit-action
      with:
        commit_message: 'New file: ${{ github.event.issue.title }}'
        commit_option: '--allow-empty'
        repository: .
        status_options: '--untracked-files=no'
        file_pattern: 'files/*'
        push_option: '--force'
        skip_dirty_check: true
        skip_fetch: true
        disable_globbing: true